services:
  - type: worker
    name: discord-listener
    env: node
    buildCommand: npm install
    startCommand: npm run discord-bot
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
